--Insert into START_MYLOOKUP (ID,CHANGED,CHANGEDBY,CREATED,CREATEDBY,VERSION,DESCRIPTION,NAME) values (1,current_date,'DEVELOPER',current_date,'DEVELOPER',1,'aa1','aa1');
--Insert into START_MYLOOKUP (ID,CHANGED,CHANGEDBY,CREATED,CREATEDBY,VERSION,DESCRIPTION,NAME) values (2,current_date,'DEVELOPER',current_date,'DEVELOPER',1,'aa2','aa2');

--Insert into START_MYDATA (ID,CHANGED,CHANGEDBY,CREATED,CREATEDBY,VERSION,MYLOOKUP_ID,VALUE) values (1,current_date,'DEVELOPER',current_date,'DEVELOPER',1,1, 1.234);
--Insert into START_MYDATA (ID,CHANGED,CHANGEDBY,CREATED,CREATEDBY,VERSION,MYLOOKUP_ID,VALUE) values (2,current_date,'DEVELOPER',current_date,'DEVELOPER',1,1, 2.234);
--Insert into START_MYDATA (ID,CHANGED,CHANGEDBY,CREATED,CREATEDBY,VERSION,MYLOOKUP_ID,VALUE) values (3,current_date,'DEVELOPER',current_date,'DEVELOPER',1,2, 3.234);
--Insert into START_MYDATA (ID,CHANGED,CHANGEDBY,CREATED,CREATEDBY,VERSION,MYLOOKUP_ID,VALUE) values (4,current_date,'DEVELOPER',current_date,'DEVELOPER',1,2, 4.234);

